zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"

kafka:
  build: docker-kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

druid:
  build: docker-druid
  ports:
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
    - "8090:8090"
  links:
    - zookeeper:zk
    - kafka:kakfa
